const data = [
  {
    category: 'css',
    question: 'Which CSS property is used to change the text color of an element?',
    answer: 'color',
    timesSeen: 0,
    timesCorrect: 0,
    memoryValue: 0.5,
  },
  {
    category: 'javascript',
    question: 'What is the built in method that allows you to add a new item to the beginning of an array?',
    answer: 'unshift',
    timesSeen: 0,
    timesCorrect: 0,
    memoryValue: 0.5,
  },
  {
    category: 'html',
    question: 'What does HTML stand for?',
    answer: 'hypertext markup language',
    timesSeen: 0,
    timesCorrect: 0,
    memoryValue: 0.5,
  },
  {
    category: 'html',
    question: 'Which HTML attribute is used to define inline styles?',
    answer: 'style',
    timesSeen: 0,
    timesCorrect: 0,
    memoryValue: 0.5,
  },
  {
    category: 'javascript',
    question: 'How do you find the number with the highest value of x and y?',
    answer: 'Math.max(x, y)',
    timesSeen: 0,
    timesCorrect: 0,
    memoryValue: 0.5,
  },
  {
    category: 'html',
    question: 'What html tag is used to draw graphics, on the fly, via scripting (<write answer like this>)?',
    answer: '<canvas>',
    timesSeen: 0,
    timesCorrect: 0,
    memoryValue: 0.5,
  },
  {
    category: 'css',
    question: 'Write a css rule set to display links(<a>) WITHOUT an underline.',
    answer: 'a{text-decoration:none;}',
    timesSeen: 0,
    timesCorrect: 0,
    memoryValue: 0.5,
  },
  {
    category: 'javascript',
    question: 'What will the following code print out?\r\n\r\nconst animals = [ \'Dodo\', \'Tiger\', \'Penguin\', \'Dodo\' ];\r\nconsole.log(animals.lastIndexOf(\'Dodo\'));',
    answer: '3',
    timesSeen: 0,
    timesCorrect: 0,
    memoryValue: 0.5,
  },
  {
    category: 'html',
    question: 'Header tags start at <h1> and end at?',
    answer: '<h6>',
    timesSeen: 0,
    timesCorrect: 0,
    memoryValue: 0.5,
  },
  {
    category: 'css',
    question: 'Which CSS function allows you to perfrom calculation to determine CSS property values?',
    answer: 'calc()',
    timesSeen: 0,
    timesCorrect: 0,
    memoryValue: 0.5,
  },
];

module.exports = data;
